!example
flowsheets: !flowsheets
  client_id: ${EPIC_CLIENT_ID}
  cookie: ${EPIC_COOKIE}
  kinds:
    score:
      flowsheet_id: ${EPIC_FLOWSHEET_ID}
      flowsheet_template_id: ${EPIC_FLOWSHEET_TEMPLATE_ID}
  password: ${EPIC_PASSWORD}
  url: ${EPIC_URL}api/epic/2011/clinical/patient/addflowsheetvalue/flowsheetvalue
  username: ${EPIC_USERNAME}
postgres: !postgres
  database: ${POSTGRES_DATABASE}
  host: ${POSTGRES_HOST}
  password: ${POSTGRES_PASSWORD}
  port: ${POSTGRES_PORT}
  schema: example
  sql: null
  username: ${POSTGRES_USERNAME}
time_zone: America/New_York
